{% set name = "phonolammps" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/phonoLAMMPS/phonoLAMMPS-{{ version }}.tar.gz
  sha256: 2f582bb4168b420115e7988869e627cc0de1951b83636800a4d050eb1985fad2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - phonopy
    - dynaphopy
    - seekpath
    - numpy

test:
  imports:
    - phonolammps
  commands:
    - pip check

about:
  home: https://github.com/abelcarreras/phonolammps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LAMMPS interface for phonon calculations using phonopy

  description: |
    Calculate the 2nd order force constants using phonopy and LAMMPS.
  doc_url: https://phonolammps.readthedocs.io/
  dev_url: https://github.com/abelcarreras/phonolammps

extra:
  recipe-maintainers:
    - jan-janssen
