{% set name = "phonolammps" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/phonoLAMMPS/{{ name }}-{{ version }}.tar.gz
  sha256: b790d18541c8625467b5f92105d81311b0a5f147806bdc04658459a9361681a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - phonopy
    - dynaphopy
    - seekpath
    - numpy

test:
  imports:
    - phonolammps
  commands:
    - pip check

about:
  home: https://github.com/abelcarreras/phonolammps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LAMMPS interface for phonon calculations using phonopy

  description: |
    Calculate the 2nd order force constants using phonopy and LAMMPS.
  doc_url: https://phonolammps.readthedocs.io/
  dev_url: https://github.com/abelcarreras/phonolammps

extra:
  recipe-maintainers:
    - jan-janssen
