{% set name = "phonolammps" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/phonoLAMMPS/{{ name }}-{{ version }}.tar.gz
  sha256: 2678a61c858af1eef02f80b6b422b0c67fe70f03ba5a751d476985aa5a39c9f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - phonopy
    - dynaphopy
    - seekpath
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - phonolammps
  commands:
    - pip check

about:
  home: https://github.com/abelcarreras/phonolammps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LAMMPS interface for phonon calculations using phonopy

  description: |
    Calculate the 2nd order force constants using phonopy and LAMMPS.
  doc_url: https://phonolammps.readthedocs.io/
  dev_url: https://github.com/abelcarreras/phonolammps

extra:
  recipe-maintainers:
    - jan-janssen
