travis:
  secure:
    BINSTAR_TOKEN: NH+03AQTeDZcZFeTTUu2/feyCtLgqTveUQU9pP2pEXbo7TP39YD5u3p+MwLXqF4py68WkfOEOb7gH08Au5xQvYS6/fgSqkfVmUW3n5XXDehqfyhll1jpcgUp8j1BLLYkSbQmNs0lJgkQu4k0uLnJOvTuI7VpbL8pLURmHwe3sjIoYiwHXX3HrpyWJh4P384KPC70thCI7KVqAgRXRsg4VnhzbJIBFU+ZtcxVLSI7xpbRrSqreNAlYe4ng037T/RQdOXqjHUWcpS7FLwq69DPtd0G3nZVpH/ZyMz6JSRF+l2JCCToy/v0RA/Tnvj6ViysrKJey08rNrUv36Vzvcf0cGs+Hq98zABVxABlATGYwC/P8RMf9aSAx0fIvFxrILcXGY6PWPRl8EBEglO0a3e/1HcDP8AA/04EOXaZDkXgUTReuNiHkdc5z3l5J137i6kBKB93W8FhMT9uf3E+Gaiqt0YVg/5J0QCzyfFHNYpMUZnudYNg+sil6q6P3A63xvkLpHwnudsxD4Q2gxeyGdpofGdMWsQcQTD/e+PCxrYNjMTuOki20/CF4Z5YSolhd+D1d3maIIsh7ALKKtaq9gYRpoJpjAK6AdrakwWo0FuGKnMfjFzxQ6yeipynZ4GLG1kKCmqaMncki47kB3mjiydo/30txf746e9EUZnONb/E3x4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
